source 'https://rubygems.org'

gem 'rails'
gem 'codemirror-rails'
gem 'terminal-table'
gem 'axlsx_rails'
gem 'simple_form'
gem 'ransack'
gem 'kaminari'

group :assets do
  gem 'uglifier'
end
