# To choose what Rails frameworks to load, and skip others:
# NOTE: Be sure this list reflects the same choices made in the gemspec
require 'rails' # NOTE: not 'rails/rails' or 'rails/all'
require 'active_model/railtie'
# require 'active_job/railtie'
require 'active_record/railtie'
# require 'active_storage/engine'
require 'action_controller/railtie'
require 'action_mailer/railtie'
# require 'action_mailbox/engine'
# require 'action_text/engine'
require 'action_view/railtie'
# require 'action_cable/engine'
require 'sprockets/railtie'
require 'rails/test_unit/railtie'
